# create container to build the app in
FROM node:12-alpine as build

# make the 'build' folder the current working directory
WORKDIR /build

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm ci

# copy project files and folders to the current working directory
COPY . .

# declare arg for the api host that the app will use.
ARG API_HOST

# build app for production with minification
RUN npm run build -- --env.api_host=${API_HOST}

# create runtime container without the build dependencies
FROM node:12-alpine as runtime

# make the 'app' folder the current working directory
WORKDIR /app

# copy index.html
COPY --from=build /build/index.html index.html

# copy across built files
COPY --from=build /build/dist dist

# install simple http server for serving static content
RUN npm install -g servor

# set user to the node user
USER node

EXPOSE 8080
CMD [ "servor" ]